version: '3.8'

services:
  structurizr:
    build:
        context: .
        dockerfile: Structurizr.Dockerfile
    image: structurizr-lite:lastest
    volumes:
        - ./structurizr:/usr/local/structurizr
    ports:
        - "8080:8080"
    # environment:
      # WORDPRESS_DB_HOST: host.docker.internal
  # ngrok:
  #   build:
  #       context: .
  #       dockerfile: Ngrok.Dockerfile
  #   image: ngrok:lastest
  #   # command:
  #   #   - "start"
  #   #   - "--all"
  #   #   - "--config"
  #   #   - "/etc/ngrok.yml"
  #   # volumes:
  #   #   - ./ngrok.yml:/etc/ngrok.yml
  #   environment:
  #     NGROK_AUTHTOKEN: 2UyRqzwje2WvwcvNxSsRhKjANbi_7yhYToVvuaLhFmKAKy26K
  #   command: http host.docker.internal:80
    
